### ISSUE TITLE
Ring camera not loading in Homekit

### ISSUE THREAD

**Issue by acorona78** [hoobs-org/HOOBS#1039]
Hello,

I recently updated HOOBS to the latest version, however the ring camera does not load and camera is not found in Homekit. I tried re-entering the token in the Ring plugin and the camera shows up momentarily in Homekit but eventually it stops working.

Thanks in advance.

**Comment by askovi** [comment]
Please post your logs

**Comment by acorona78** [comment]
@askovi I am new to HOOBS, so I hope I pulled the correct log.

Here is the log that keeps repeating.

1/19/2021, 3:02:24 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/dings/active.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/19/2021, 3:02:24 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/update_all.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/19/2021, 3:02:24 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/19/2021, 3:02:24 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/ring_devices.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/19/2021, 3:02:24 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/doorbots/12896182/live_view.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/19/2021, 3:02:26 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/snapshots/timestamps.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...
1/19/2021, 3:02:26 PM [Ring] Failed to reach Ring server at https://api.ring.com/clients_api/doorbots/12896182/live_view.  Stream closed with error code NGHTTP2_ENHANCE_YOUR_CALM.  Trying again in 5 seconds...

**Comment by askovi** [comment]
this should be solved by upgrading node. Here are the steps to do that:

1. Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: ssh hoobs@hoobs.local

Type yes to accept the certificate key then press enter. When prompted for password, type hoobsadmin

On Windows, use Putty with the same credentials as above.

2. After successfully logging in, paste the following command:

` wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts`

**Comment by acorona78** [comment]
Hello,

I was able to login via SSH and follow the steps above, however HOOBS is not responding anymore and I am unable to reach the HOOBS local site. I have tried power cycling to reset, I am able to get into hoobs local briefly, but then HOOBS stops responding. Any suggestions on what else to try?

**Comment by EddieDSuza** [comment]
Login to the HOOBS Box via SSH on your computer.

On MacOS use the Terminal app and type: `ssh hoobs@hoobs.local`

Type yes to accept the certificate key then press enter. When prompted for password, type **hoobsadmin**
Once logged in you will see in green text hoobs@hoobs on the left side of the terminal.

Paste these commands in sequence once you see that - 

`sudo npm uninstall -g @hoobs/hoobs`

`sudo npm install -g --unsafe-perm @hoobs/hoobs`

`sudo reboot`

Give it a couple of minutes and the access http://hoobs.local via your preferred web page

**Comment by acorona78** [comment]
I am able to run the command, but still unable to login, this is the log below,

bufferutil@4.0.3 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/bufferutil
node-gyp-build


node-pty@0.9.0 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
node scripts/install.js

ke: Entering directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'
CXX(target) Release/obj.target/pty/src/unix/pty.o
/src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
/src/unix/pty.cc:486:43: warning: ‘void* memset(void*, int, size_t)’ writing to an object of type

lass Nan::Persistent<v8::Function>’ with no trivial copy-assignment [-Wclass-memaccess]
 memset(&baton->cb, -1, sizeof(baton->cb));
                                         ^
 file included from ../../nan/nan.h:405,
               from ../src/unix/pty.cc:20:
/../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Function>’ declared here
emplate<typename T, typename M> class Persistent :
                                      ^~~~~~~~~~
 file included from ../../nan/nan.h:56,
               from ../src/unix/pty.cc:20:
/src/unix/pty.cc: At global scope:
oot/.cache/node-gyp/14.15.1/include/node/node.h:758:43: warning: cast between incompatible functio

types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>

} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*

} [-Wcast-function-type]
     (node::addon_register_func) (regfunc),                          \
                                         ^
oot/.cache/node-gyp/14.15.1/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’

 NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
 ^~~~~~~~~~~~~
/src/unix/pty.cc:708:1: note: in expansion of macro ‘NODE_MODULE’
ODE_MODULE(pty, init)
~~~~~~~~~~
SOLINK_MODULE(target) Release/obj.target/pty.node
COPY Release/pty.node
ke: Leaving directory '/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty/build'

utf-8-validate@5.0.4 install /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/utf-8-validate
node-gyp-build

           ......] / postinstall:@hoobs/hoobs: sill doSerial postinstall 1712
           ......] / postinstall:listenercount: info lifecycle listenercount@1.0.1~postinstall: l
           ......] \ postinstall:sisteransi: info lifecycle sisteransi@1.0.5~postinstall: sistera
           ......] \ postinstall:express-ws: info lifecycle express-ws@4.0.0~postinstall: express


node-pty@0.9.0 postinstall /usr/local/lib/node_modules/@hoobs/hoobs/node_modules/node-pty
node scripts/post-install.js


@hoobs/hoobs@3.3.2 postinstall /usr/local/lib/node_modules/@hoobs/hoobs
bin/hoobs upgrade

@hoobs/hoobs@3.3.2
ded 214 packages from 195 contributors in 44.752s

obs@hoobs: ~hoobs@hoobs:~ $ sudo reboot
nnection to hoobs.local closed by remote host.
nnection to hoobs.local closed.

**Comment by EddieDSuza** [comment]
Were you able to fix the issue or refreshed the Card ?

**Comment by acorona78** [comment]
Still experiencing issue, but I will re-flash card and report back.

**Comment by acorona78** [comment]
I re-flashed the SD card and that helped. Thank you.
