### ISSUE TITLE
Unable to upgrade from 4.0.100

### ISSUE THREAD

**Issue by wiible** [hoobs-org/HOOBS#1561]
**Description**
When I upgrade I get a certificate error and upgrade does not happen

**Version**
4.0.100

**Did you upgrade**
Please let us know if you upgraded from a previous version.
- [ ] Yes
- [ *] No

**Pervious version**
If you upgraded, please let us know your previous version.

**Did you orginally upgrade to HOOBS 3 from HOOBS 2.1.1?**
Did you perform an upgrade from HOOBS 2.1.1? Some things are different.
- [ ] Yes
- [* ] No

**What device are you using?**
Please let us know the device you are running HOOBS on.
- [ ] HOOBS Box
- [ *] HOOBS SD Card
- [ ] Custom Install

**If this is a custom install, what's your operating system?**
Please let us know what operating system and version you are using. Ex. Fedora 30 or macOS Catalina.

**List your plugins**
RING
EWELINK

**Post your config**

* Remove any passwords from the config file. This is public.

```
    "accessories": [],
    "platforms": [
        {
            "platform": "Ring",
            "email": "",
            "password": "",
            "refreshToken": "",
            "alarmOnEntryDelay": false,
            "hideLightGroups": false,
            "hideDoorbellSwitch": true,
            "hideCameraMotionSensor": false,
            "hideCameraSirenSwitch": true,
            "hideInHomeDoorbellSwitch": true,
            "hideAlarmSirenSwitch": true,
            "hideUnsupportedServices": true,
            "showPanicButtons": false,
            "debug": true
        }
    ]
}


    "accessories": [],
    "platforms": [
        {
            "platform": "eWeLink",
            "name": "eWeLink",
            "debug": false,
            "debugReqRes": false,
            "disableHTTPRefresh": false,
            "disablePlugin": false,
            "inUsePowerThreshold": 0,
            "lowBattThreshold": 25,
            "sensorTimeDifference": 120,
            "hideZBLDPress": false,
            "countryCode": "",
            "username": "",
            "password": "",
            "mode": "auto"
        }
    ]
}
```

**Post your log**
You can get the log from the interface. This is in the Log section.

```
04/10/2021, 11:50:38upgrading node
04/10/2021, 11:50:39Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
04/10/2021, 11:50:39Hit:2 http://archive.raspberrypi.org/debian buster InRelease
04/10/2021, 11:50:39Ign:3 https://dl.hoobs.org/deb/stable buster InRelease
04/10/2021, 11:50:39Ign:4 https://deb.nodesource.com/node_14.x buster InRelease
04/10/2021, 11:50:39Hit:5 https://dl.yarnpkg.com/debian stable InRelease
04/10/2021, 11:50:39Err:6 https://deb.nodesource.com/node_14.x buster Release
04/10/2021, 11:50:39Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 62.252.115.64 443]
04/10/2021, 11:50:39Err:7 https://dl.hoobs.org/deb/stable buster Release
04/10/2021, 11:50:39Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:50:40Reading package lists...
04/10/2021, 11:50:44E
04/10/2021, 11:50:44: The repository 'https://deb.nodesource.com/node_14.x buster Release' no longer has a Release file.
04/10/2021, 11:50:44E: The repository 'https://dl.hoobs.org/deb/stable buster Release' no longer has a Release file.
04/10/2021, 11:50:44Reading package lists...
04/10/2021, 11:50:46Building dependency tree...
04/10/2021, 11:50:47Reading state information...
04/10/2021, 11:50:48curl is already the newest version (7.64.0-4+deb10u2).
04/10/2021, 11:50:48g++ is already the newest version (4:8.3.0-1+rpi2).
04/10/2021, 11:50:48gcc is already the newest version (4:8.3.0-1+rpi2).
04/10/2021, 11:50:48git is already the newest version (1:2.20.1-2+deb10u3).
04/10/2021, 11:50:48make is already the newest version (4.2.1-1.2).
04/10/2021, 11:50:48python3 is already the newest version (3.7.3-1).
04/10/2021, 11:50:48tar is already the newest version (1.30+dfsg-6).
04/10/2021, 11:50:48The following package was automatically installed and is no longer required:
04/10/2021, 11:50:48nodejs-doc
04/10/2021, 11:50:48Use 'apt autoremove' to remove it.
04/10/2021, 11:50:48The following packages will be upgraded:
04/10/2021, 11:50:48nodejs
04/10/2021, 11:50:481 upgraded, 0 newly installed, 0 to remove and 163 not upgraded.
04/10/2021, 11:50:48Need to get 23.0 MB of archives.
04/10/2021, 11:50:48After this operation, 1,272 kB of additional disk space will be used.
04/10/2021, 11:50:48Err:1 https://deb.nodesource.com/node_14.x buster/main armhf nodejs armhf 14.18.0-deb-1nodesource1
04/10/2021, 11:50:48Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 62.252.115.83 443]
04/10/2021, 11:50:48E: Failed to fetch https://deb.nodesource.com/node_14.x/pool/main/n/nodejs/nodejs_14.18.0-deb-1nodesource1_armhf.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 62.252.115.83 443]
04/10/2021, 11:50:48E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
04/10/2021, 11:50:48upgrading cli
04/10/2021, 11:50:49Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
04/10/2021, 11:50:49Hit:2 http://archive.raspberrypi.org/debian buster InRelease
04/10/2021, 11:50:49Ign:3 https://dl.hoobs.org/deb/stable buster InRelease
04/10/2021, 11:50:49Ign:4 https://deb.nodesource.com/node_14.x buster InRelease
04/10/2021, 11:50:49Hit:5 https://dl.yarnpkg.com/debian stable InRelease
04/10/2021, 11:50:49Err:6 https://dl.hoobs.org/deb/stable buster Release
04/10/2021, 11:50:49Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
04/10/2021, 11:50:49Err:7 https://deb.nodesource.com/node_14.x buster Release
04/10/2021, 11:50:49Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 62.252.115.64 443]
04/10/2021, 11:50:50Reading package lists...
04/10/2021, 11:50:53E: The repository 'https://dl.hoobs.org/deb/stable buster Release' no longer has a Release file.
04/10/2021, 11:50:53E: The repository 'https://deb.nodesource.com/node_14.x buster Release' no longer has a Release file.
04/10/2021, 11:50:53Reading package lists...
04/10/2021, 11:50:53Building dependency tree...
04/10/2021, 11:50:53Reading state information...
04/10/2021, 11:50:54The following package was automatically installed and is no longer required:
04/10/2021, 11:50:54nodejs-doc
04/10/2021, 11:50:54Use 'apt autoremove' to remove it.
04/10/2021, 11:50:54The following packages will be upgraded:
04/10/2021, 11:50:54hoobs-cli
04/10/2021, 11:50:541 upgraded, 0 newly installed, 0 to remove and 163 not upgraded.
04/10/2021, 11:50:54Need to get 69.9 kB of archives.
04/10/2021, 11:50:54After this operation, 0 B of additional disk space will be used.
04/10/2021, 11:50:54Err:1 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-cli all 4.0.46
04/10/2021, 11:50:54Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:50:54E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-cli/hoobs-cli_4.0.46_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:50:54E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
04/10/2021, 11:50:54upgrading gui
04/10/2021, 11:50:55Hit:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
04/10/2021, 11:50:55Hit:2 http://archive.raspberrypi.org/debian buster InRelease
04/10/2021, 11:50:55Ign:3 https://deb.nodesource.com/node_14.x buster InRelease
04/10/2021, 11:50:55Ign:4 https://dl.hoobs.org/deb/stable buster InRelease
04/10/2021, 11:50:55Hit:5 https://dl.yarnpkg.com/debian stable InRelease
04/10/2021, 11:50:55Err:6 https://deb.nodesource.com/node_14.x buster Release
04/10/2021, 11:50:55Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 62.252.115.83 443]
04/10/2021, 11:50:55Err:7 https://dl.hoobs.org/deb/stable buster Release
04/10/2021, 11:50:55Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
04/10/2021, 11:50:59Reading package lists...
04/10/2021, 11:51:02E: The repository 'https://deb.nodesource.com/node_14.x buster Release' no longer has a Release file.
04/10/2021, 11:51:02E: The repository 'https://dl.hoobs.org/deb/stable buster Release' no longer has a Release file.
04/10/2021, 11:51:02Reading package lists...
04/10/2021, 11:51:03Building dependency tree...
04/10/2021, 11:51:03Reading state information...
04/10/2021, 11:51:04The following package was automatically installed and is no longer required:
04/10/2021, 11:51:04nodejs-doc
04/10/2021, 11:51:04Use 'apt autoremove' to remove it.
04/10/2021, 11:51:04The following packages will be upgraded:
04/10/2021, 11:51:04hoobs-gui
04/10/2021, 11:51:041 upgraded, 0 newly installed, 0 to remove and 163 not upgraded.
04/10/2021, 11:51:04Need to get 13.2 MB of archives.
04/10/2021, 11:51:04After this operation, 0 B of additional disk space will be used.
04/10/2021, 11:51:04Err:1 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-gui all 4.0.91
04/10/2021, 11:51:04Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:51:05E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-gui/hoobs-gui_4.0.91_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:51:05E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
04/10/2021, 11:51:05upgrading hoobsd
04/10/2021, 11:51:07Hit:1 http://archive.raspberrypi.org/debian buster InRelease
04/10/2021, 11:51:07Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
04/10/2021, 11:51:07Ign:3 https://deb.nodesource.com/node_14.x buster InRelease
04/10/2021, 11:51:07Ign:4 https://dl.hoobs.org/deb/stable buster InRelease
04/10/2021, 11:51:07Hit:5 https://dl.yarnpkg.com/debian stable InRelease
04/10/2021, 11:51:07Err:6 https://deb.nodesource.com/node_14.x buster Release
04/10/2021, 11:51:07Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 62.252.115.64 443]
04/10/2021, 11:51:07Err:7 https://dl.hoobs.org/deb/stable buster Release
04/10/2021, 11:51:07Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:51:12Reading package lists...
04/10/2021, 11:51:15E: The repository 'https://deb.nodesource.com/node_14.x buster Release' no longer has a Release file.
04/10/2021, 11:51:15E: The repository 'https://dl.hoobs.org/deb/stable buster Release' no longer has a Release file.
04/10/2021, 11:51:15Reading package lists...
04/10/2021, 11:51:15Building dependency tree...
04/10/2021, 11:51:15Reading state information...
04/10/2021, 11:51:16The following package was automatically installed and is no longer required:
04/10/2021, 11:51:16nodejs-doc
04/10/2021, 11:51:16Use 'apt autoremove' to remove it.
04/10/2021, 11:51:16The following packages will be upgraded:
04/10/2021, 11:51:16hoobsd
04/10/2021, 11:51:181 upgraded, 0 newly installed, 0 to remove and 163 not upgraded.
04/10/2021, 11:51:18Need to get 107 kB of archives.
04/10/2021, 11:51:18After this operation, 0 B of additional disk space will be used.
04/10/2021, 11:51:18Err:1 https://dl.hoobs.org/deb/stable buster/main armhf hoobsd all 4.0.104
04/10/2021, 11:51:18Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:51:18E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobsd/hoobsd_4.0.104_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
04/10/2021, 11:51:18E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Additional context**

**Comment by joftrobert** [comment]
Same issue here - certificate validation issue.

Per closed thread:

`if you are seeing a certificate issue run this
wget -qO- https://dl.hoobs.org/stable | sudo -E bash -`

That did nothing.

**Comment by mkellsy** [comment]
Run it again
```
wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
```

It will fix the NodeSource repo.
Then run this.
```
sudo apt install -y hoobsd hoobs-cli hoobs-gui
```

This will upgrade everything.

**Comment by wiible** [comment]
Thanks for your comment.  I have run commands as you say, but still no luck.  This is what I get:

`hoobs@hoobs:~ $ wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
hoobs@hoobs:~ $ sudo apt install -y hoobsd hoobs-cli hoobs-gui
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  nodejs-doc
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  hoobs-cli hoobs-gui hoobsd
3 upgraded, 0 newly installed, 0 to remove and 161 not upgraded.
Need to get 13.4 MB of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-cli all 4.0.46
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
Err:2 https://dl.hoobs.org/deb/stable buster/main armhf hoobsd all 4.0.104
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
Err:3 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-gui all 4.0.91
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-cli/hoobs-cli_4.0.46_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobsd/hoobsd_4.0.104_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-gui/hoobs-gui_4.0.91_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.109.153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
hoobs@hoobs:~ $ `

**Comment by mkellsy** [comment]
When you run this
```
wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
```

What's the output. The log you posted is the effect, I'm looking for the cause.

**Comment by wiible** [comment]
there is no output.  I have copied exactly what shows in terminal.

**Comment by mkellsy** [comment]
It should look something like this
```
Get:1 https://dl.hoobs.org/deb/stable buster InRelease [3,022 B]
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://security.debian.org/debian-security buster/updates InRelease
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 https://deb.nodesource.com/node_14.x buster InRelease
Hit:6 http://deb.debian.org/debian buster-updates InRelease
Fetched 3,022 B in 0s (7,989 B/s)
Reading package lists... Done
deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x buster main
deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x buster main
deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main
deb [signed-by=/usr/share/keyrings/hoobs.gpg] https://dl.hoobs.org/deb/stable/ buster main
Hit:1 http://deb.debian.org/debian buster InRelease
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 https://dl.hoobs.org/deb/stable buster InRelease [3,022 B]
Hit:5 https://dl.yarnpkg.com/debian stable InRelease
Hit:6 https://deb.nodesource.com/node_14.x buster InRelease
Fetched 3,022 B in 0s (10.8 kB/s)
Reading package lists... Done
```

You may have to wait an hour or so, I just pushed a change to the script and it may take a bit for the CDN to propagate the change.

When you run this what does it say?
```
lsb_release -c -s
```

And this
```
uname -m
```

**Comment by wiible** [comment]
`hoobs@hoobs:~ $ lsb_release -c -s`
buster

`hoobs@hoobs:~ $ uname -m`
armv7l

**Comment by wiible** [comment]
FYI - this is the output

hoobs@hoobs:~ $ `wget -O- https://dl.hoobs.org/stable | sudo -E bash -`
--2021-10-05 15:37:58--  https://dl.hoobs.org/stable
Resolving dl.hoobs.org (dl.hoobs.org)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to dl.hoobs.org (dl.hoobs.org)|185.199.108.153|:443... connected.
ERROR: The certificate of ‘dl.hoobs.org’ is not trusted.
ERROR: The certificate of ‘dl.hoobs.org’ has expired.

**Comment by wiible** [comment]
So I left it for 3 hours and I still get the same (nothing when quiet mode selected):

hoobs@hoobs:~ $ `wget -qO- https://dl.hoobs.org/stable | sudo -E bash -`
hoobs@hoobs:~ $ `wget -O- https://dl.hoobs.org/stable | sudo -E bash -`
--2021-10-05 18:06:33--  https://dl.hoobs.org/stable
Resolving dl.hoobs.org (dl.hoobs.org)... 185.199.109.153, 185.199.110.153, 185.199.111.153, ...
Connecting to dl.hoobs.org (dl.hoobs.org)|185.199.109.153|:443... connected.
ERROR: The certificate of ‘dl.hoobs.org’ is not trusted.
ERROR: The certificate of ‘dl.hoobs.org’ has expired.

**Comment by mkellsy** [comment]
I’m looking into it

**Comment by mkellsy** [comment]
I made an update. It should clear key errors before repairing the repos.

Run this again
```
wget -qO- https://dl.hoobs.org/stable | sudo -E bash -
```

Again this might take some time to update the CDN.

**Comment by wiible** [comment]
Hi

Thanks for trying to sort this issue out.

I have tried again and same errors as before.  I rebooted before running it and tried the install again after but the same errors about dl.hoobs.org certificate expired

hoobs@hoobs:~ $ `wget -qO- https://dl.hoobs.org/stable | sudo -E bash -`
hoobs@hoobs:~ $ s`udo apt install -y hoobsd hoobs-cli hoobs-gui`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  nodejs-doc
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  hoobs-cli hoobs-gui hoobsd
3 upgraded, 0 newly installed, 0 to remove and 161 not upgraded.
Need to get 13.4 MB of archives.
After this operation, 0 B of additional disk space will be used.
Err:1 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-cli all 4.0.46
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
Err:2 https://dl.hoobs.org/deb/stable buster/main armhf hoobsd all 4.0.104
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
Err:3 https://dl.hoobs.org/deb/stable buster/main armhf hoobs-gui all 4.0.91
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-cli/hoobs-cli_4.0.46_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobsd/hoobsd_4.0.104_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
E: Failed to fetch https://dl.hoobs.org/deb/stable/pool/main/h/hoobs-gui/hoobs-gui_4.0.91_all.deb  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.199.108.153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by cbdoc** [comment]
I'm having this exact issue. 

The last command that @mkellsy offered (no -E flag) doesn't resolve the issue. Issuing command without the q flag gives:
`wget -O- https://dl.hoobs.org/stable | sudo bash -
--2021-10-06 10:22:30--  https://dl.hoobs.org/stable
Resolving dl.hoobs.org (dl.hoobs.org)... 185.199.109.153, 185.199.110.153, 185.199.111.153, ...
Connecting to dl.hoobs.org (dl.hoobs.org)|185.199.109.153|:443... connected.
ERROR: The certificate of ‘dl.hoobs.org’ is not trusted.
ERROR: The certificate of ‘dl.hoobs.org’ has expired.`

**Comment by mkellsy** [comment]
Try rebooting.

If that doesn't help try this
```
curl -kfsSL https://dl.hoobs.org/stable | sudo bash -
```

See the issue is your device is not recognizing GitHub's SSL certificate. (dl.hoobs.org is hosted on GitHub)

**Comment by mkellsy** [comment]
I had to dig this up. Raspbian used to have SSL issues. The old fix for this is to run this command
```
wget -O /etc/ssl/certs/cacert.pem https://curl.haxx.se/ca/cacert.pem
```

You can do this or re-flash to a newer version of Raspbian.
We have a new image here https://support.hoobs.org/downloads/image

**Comment by wiible** [comment]
Thanks for all your help.  Ran that command and got the below, if I reflash do I have to set everything up again?:

hoobs@hoobs:~ $ `wget -O /etc/ssl/certs/cacert.pem https://curl.haxx.se/ca/cacert.pem`
/etc/ssl/certs/cacert.pem: Permission denied

**Comment by mkellsy** [comment]
Do a `sudo -i` first then run
```
wget -O /etc/ssl/certs/cacert.pem https://curl.haxx.se/ca/cacert.pem
```
and then `exit`

**Comment by mkellsy** [comment]
That's the issue. The main SSL certificate authority is not trusted.

You can use curl to ignore the bad certificate. Here's the command
```
sudo curl -ko /etc/ssl/certs/cacert.pem https://curl.haxx.se/ca/cacert.pem
```

If that does work. Try the repo refresh script
```
wget -qO- https://dl.hoobs.org/stable | sudo bash -
```

If that doesn't work you can try to re-flash

From above you are on 4.0. Good news is you can make a backup.
Login to the UI and go to Menu -> Hub Settings
Then click "Backup"

After the file downloads. You can re-flash to the latest base OS (which doesn't have the ca-certificate error)
When it comes back up, you can just "Disable Logins" then restore from the Hub Settings.
It will retain you plugins configs passwords and HomeKit parings.

**Comment by mkellsy** [comment]
Also @wiible thanks for helping me figure this out.

**Comment by wiible** [comment]
Hi All 

I found a fix to save re-installing

from terminal:

`sudi -i`
`apt-get update; apt-get install libgnutls30`
then go back to dashboard and update as usual.
