### ISSUE TITLE
Stuck on Initialisation

### ISSUE THREAD

**Issue by homohurre123** [hoobs-org/HOOBS#221]
I have the same issue as https://github.com/hoobs-org/HOOBS/issues/100
I tried the installation but although it worked, I'm still stuck on the starting screen just with a nicer interface... I was about to completely reinstall it from scratch but I don't seem to be able to download the image... Paypal pops up and disappears right after and then nothing happens...

**Comment by homohurre123** [comment]
Nevermind I fixed it by entering 
rm -fR ~/.hoobs
hoobs
in terminal.
https://github.com/hoobs-org/HOOBS/issues/112

**Comment by mkellsy** [comment]
This was fixed in beta 68

**Comment by homohurre123** [comment]
Well it seemed to work but I'm for some reason unable to install any  plugins now. I tried installing the harmony plugin (the web socket... one) and fritz-platform but both didn't work out. First over the interface where I didn't get any feedback if it worked and nothing changed and over the terminal where I got this message for the fritz plugin:
"Use uuid module instead
+ homebridge-fritz-platform@4.1.0
updated 1 package in 19.285s"

and for the Harmony one I got this:
"path /home/hoobs/.npm/_cacache/index-v5/43/68
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/43/68'
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/43/68']
npm ERR!   cause:
npm ERR!    { Error: EACCES: permission denied, mkdir '/home/hoobs/.npm/_cacache/index-v5/43/68'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'mkdir',
npm ERR!      path: '/home/hoobs/.npm/_cacache/index-v5/43/68' },
npm ERR!   isOperational: true,
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, mkdir \'/home/hoobs/.npm/_cacache/index-v5/43/68\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/hoobs/.npm/_cacache/index-v5/43/68',
npm ERR!   parent: 'promise.prototype.finally' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended)."


to be honest I'm fine to start from scratch too but I can't download the image for my sd anymore after I canceled  the download the first time I tried. (Mac OS 10.15) (using Raspberry pi 3 for hoobs)

**Comment by homohurre123** [comment]
I started from scratch now so no need to invest your time :)

**Comment by mkellsy** [comment]
You npm cache is corrupt. Mainly from using sudo. To fix.

```
sudo rm -fR ~/.npm
```

Then run

```
npm cache clear
```

That should do the trick.

**Comment by grabson79** [comment]
I have the same problem, tried 
sudo npm install -g --unsafe-perm @hoobs/hoobs
but it did not resolved it.

I now tried 
rm -fR ~/.hoobs
hoobs

and it is back and running but all my accessories disappeared and the config.json is empty 
Is there any way to migrate the previous config file?
